version: "3.9"

services:
  chat-app-be:
    build: ./
    env_file:
      - path: ./.env
        required: true
    environment:
      - IS_DOCKER=true
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:7.0
    env_file:
      - path: ./.env
        required: true
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - mongodata:/data/db

volumes:
  mongodata:
    name: mongodata
